---

species: 
  - Myotis_lucifugus
  - Myotis_evotis
  - Myotis_thysanodes
  - Myotis_volans
  - Myotis_californicus
  - Myotis_auriculus
  - Myotis_occultus
  - Myotis_velifer
  - Myotis_yumanensis

species_abbr:
  Myotis_lucifugus: "M_lucifugus"
  Myotis_evotis: "M_evotis"
  Myotis_thysanodes: "M_thysanodes"
  Myotis_volans: "M_volans"
  Myotis_californicus: "M_californicus"
  Myotis_auriculus: "M_auriculus"
  Myotis_occultus: "M_occultus"
  Myotis_velifer: "M_velifer"
  Myotis_yumanensis: "M_yumanensis"

ccs_opts:
  - "minPasses3_minRQ0.99"

hifi_opts:
  - "l2"

conf_hic:
  - "bp"
  - "hic"

conf_scaffold:
  - ""
  - "_scaffolds_final"
