---
title: "536MammalsStats"
author: "docmanny"
date: "2023-10-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(tidyverse)
library(ggpubr)
library(ggsci)
library(ggrepel)
library(kableExtra)
# library(UpSetR)
library(ComplexHeatmap)
```

```{r data}
df.lq <- read_tsv('../data/lifehistory/manny_mammal_agedata_harmonized.withLQ_hasAli.tsv')

ali.species.lists <- jsonlite::read_json('../data/allgenes_reformat.json') %>% 
  lapply(function(x){x %>% .[which(.!="")]})
```


```{r Table of sampling depth given a known LQ in each clade}
df.lq %>% 
  filter(!is.na(LQ)) %>% 
  group_by(Order) %>% 
  summarize(
    pc.sampled = sum(has.ali)/length(has.ali), 
    n.LQ = n(), 
    n.withAli = sum(has.ali)
  ) %>% 
  mutate(
    pc.sampled = factor(
      scales::label_percent(accuracy=1)(pc.sampled),
      levels=scales::label_percent(accuracy=1)(sort(pc.sampled)) %>% unique
    )
  ) %>% 
  arrange(desc(pc.sampled), desc(n.LQ)) %>% 
  ggtexttable()
```

```{r species hist}
ali.species.mat <- UpSetR::fromList(ali.species.lists)
ali.species.n <- sapply(ali.species.lists, length)

df.ali.species.n <- ali.species.n %>% 
  tibble(gene = names(.), count = .) %>% 
  arrange(desc(count)) %>% 
  mutate(gene = factor(gene, levels=gene))

df.ali.species.n %>% 
  summary

median.count <- median(df.ali.species.n$count)
median.gene <- df.ali.species.n %>% 
  filter(count == 510) %>% 
  tail(n=1) %>% 
  pull(gene)

genes.top3Q <- df.ali.species.n %>% 
  filter(count >= 452) 

n.genes.top3Q <- genes.top3Q %>% 
  nrow

gene.top3Q <- genes.top3Q %>% 
  tail(n=1) %>% 
  pull(gene)

df.ali.species.n %>% 
  ggplot(
    aes(
      x=gene,
      y=count
    )
  ) + 
  geom_bar(stat = 'identity') +
  geom_hline(yintercept = median.count, lty='dashed', color='red') + 
  geom_segment(aes(x=median.gene, xend=median.gene, y=median.count, yend=0), color='red') + 
  geom_label(aes(label=str_c('Median:\n', median.count,"/536 Species"), x=median.gene, y=median.count+20)) + 
  geom_hline(yintercept = 452, lty='dashed', color='blue') + 
  geom_segment(aes(x=gene.top3Q, xend=gene.top3Q, y=452, yend=0), color='blue') + 
  geom_label(aes(label=str_c('Q3:452/536\n', '#Genes: ', n.genes.top3Q, '/', length(gene)), x=gene.top3Q, y=452-20)) + 
  theme_pubr() + 
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
```

```{r species subsets}

laurasiatheria.orders <- c(
  "Chiroptera",
  "Perissodactyla",
  "Cetacea",
  "Artiodactyla",
  "Carnivora",
  "Pholidota",
  "Erinaceomorpha"
)

outgroup.orders <- c(
  "Rodentia",
  "Primates",
  "Sirenia",
  "Proboscidea",
  "Hyracoidea"
)

df.lq.laurasiatheria <- df.lq %>% 
  filter(Order %in% laurasiatheria.orders)

df.lq.outgroup <- df.lq %>% 
  filter(Order %in% outgroup.orders)

species.out.ali.lq <- c(
  # Rodents
  'Mus_musculus',
  'Mus_minutoides',
  'Rattus_rattus',
  'Rattus_norvegicus',
  'Peromyscus_leucopus',
  'Peromyscus_californicus',
  'Fukomys_damarensis',
  'Capromys_pilorides',
  'Heterocephalus_glaber',
  'Cavia_aperea',
  'Cavia_tschudii',
  'Cavia_porcellus',
  # Paenungulates
  'Heterohyrax_brucei',
  'Procavia_capensis',
  'Dugon_dugon',
  'Trichechus_manatus',
  'Loxodonta_africana',
  'Elephas_maximus',
  # Primates
  'Pan_troglodytes',
  'Pan_paniscus',
  'Homo_sapiens',
  'Gorilla_gorilla'
)

```
