---
title: "mash-dist"
author: "Juan M Vazquez (docmanny)"
date: "2022-12-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(ape)
library(phangorn)
library(tidyverse)
library(ggtree)
library(ggnewscale)
library(ComplexHeatmap)

species = c(
  "Myotis_occultus",
  "Myotis_lucifugus",
  "Myotis_evotis",
  "Myotis_thysanodes",
  "Myotis_auriculus",
  "Myotis_californicus",
  "Myotis_yumanensis",
  "Myotis_velifer",
  "Myotis_volans"
  )

species_genome = c(
  "Myotis_auriculus" = "mMyoAui1.cleaned",
  "Myotis_californicus" = "mMyoCai1.cleaned",
  "Myotis_occultus" = "mMyoOcc1.cleaned",
  "Myotis_lucifugus" = "mMyoLuc1.cleaned",
  "Myotis_yumanensis" = "mMyoYum1.cleaned",
  "Myotis_volans" = "mMyoVol1.cleaned",
  "Myotis_velifer" = "mMyoVel1.cleaned",
  "Myotis_evotis" = "mMyoEvo1.cleaned",
  "Myotis_thysanodes" = "mMyoThy1.cleaned"
)

genome_species = c(
  "mMyoAui1.cleaned" = "Myotis_auriculus",
  "mMyoCai1.cleaned" = "Myotis_californicus",
  "mMyoOcc1.cleaned" = "Myotis_occultus",
  "mMyoLuc1.cleaned" = "Myotis_lucifugus",
  "mMyoYum1.cleaned" = "Myotis_yumanensis",
  "mMyoVol1.cleaned" = "Myotis_volans",
  "mMyoVel1.cleaned" = "Myotis_velifer",
  "mMyoEvo1.cleaned" = "Myotis_evotis",
  "mMyoThy1.cleaned" = "Myotis_thysanodes"
)
```

```{r}
tree.timetree <- read.tree('../../data/tree/species_timetree.nwk') %>% 
  keep.tip(species)

p.tree.timetree <- ape::rotateConstr(tree.timetree, species) %>% 
  ggtree()

p.tree.timetree + 
  theme_tree() + 
  xlim_tree(c(NA,20)) + 
  geom_tiplab() + 
  theme_tree()
```


```{r}
dist_mat <- read_tsv(file = '../../data/mash_matrix_full.tsv') %>% 
  rename(all_of(species_genome)) %>% 
  mutate(`...1`= genome_species[`...1`]) %>% 
  column_to_rownames('...1') %>% 
  as.matrix() %>% 
  as.dist()

```

```{r}
tree.nj <- ape::nj(dist_mat)

ggtree(tree.nj, layout = "ape") +
  geom_tiplab()
  
```

```{r}
tree.upgma <- phangorn::upgma(dist_mat)

p.tree.upgma <- ape::rotateConstr(tree.upgma, species) %>% 
  ggtree()

p.tree.upgma +
  geom_tiplab() + 
  theme_tree() + 
  xlim_tree(c(NA, 0.02))

```

```{r cophyloplot with ape}
cotree.upgma <- ape::rotateConstr(tree.upgma, species)
cotree.timetree <- ape::rotateConstr(tree.timetree, species)

assoc.mat <- cbind(cotree.timetree$tip.label,cotree.timetree$tip.label)
ape::cophyloplot(x = cotree.upgma, y= cotree.timetree, assoc = assoc.mat)


```

```{r cophyloplot with ggtree}
p.tree.timetree.cladeogram <- tree.timetree %>% 
  # ape::rotateConstr(species) %>% 
  ggtree(branch.length = 'none') %>% 
  rotate(tree_view = ., node = 15) %>% 
  rotate(tree_view = ., node = 16) %>% 
  rotate(tree_view = ., node = 11)

p.tree.upgma.cladeogram <- ape::rotateConstr(tree.upgma, species) %>% 
  ggtree(branch.length = 'none')

cotree.upgma.dat <- p.tree.upgma.cladeogram$data
cotree.timetree.dat <- p.tree.timetree.cladeogram$data

cotree.upgma.dat$x <- max(cotree.upgma.dat$x) - cotree.upgma.dat$x + max(cotree.timetree.dat$x) + 50

dd <- bind_rows(cotree.timetree.dat, cotree.upgma.dat) %>% 
  filter(!is.na(label)) %>% 
  arrange(label, x,y)

color.subclades = c(
  "Myotis_lucifugus" = "#1B9E77",
  "Myotis_occultus" = "#1B9E77",
  "Myotis_volans" = "#1B9E77",
  "Myotis_evotis" = "#D95F02",
  "Myotis_thysanodes" = "#D95F02",
  "Myotis_auriculus" = "#7570B3",
  "Myotis_californicus" = "#7570B3",
  "Myotis_yumanensis" = "#E7298A",
  "Myotis_velifer" = "#E7298A"
  )

p.cotree <- p.tree.timetree.cladeogram +
  geom_line(aes(x,y, group=label, color=label), data=dd) + 
  geom_tree(data=cotree.upgma.dat) + 
  geom_tiplab() + 
  geom_tiplab(data=cotree.upgma.dat, hjust = 1) + 
  scale_color_manual(values=color.subclades) + 
  guides(color=guide_none())
  # ggnewscale::new_scale_fill() +
  # geom_hilight(
  #        data = d2,
  #        mapping = aes(
  #           subset = node %in% c(38, 48, 58),
  #           node=node,
  #           fill=as.factor(node))
  # ) +
  # labs(fill = "clades for tree in right" )
```

```{r}
tree.upgma %>% keep.tip(c("Myotis_volans", "Myotis_evotis", "Myotis_thysanodes")) %>% ggtree() + geom_tiplab() + xlim_tree(c(NA,0.05))
```

```{r}
ape::root.phylo(tree.nj, node = 16) %>% drop.tip(c("Myotis_californicus", "Myotis_auriculus")) %>% ggtree() + geom_tiplab() + geom_nodelab(aes(label=node), hjust=-1) + xlim_tree(c(NA,0.05))
```

## By chromosome:

```{r}
dist.chr <- read_csv("../../analyses/pangenome/output/mash-triangle/neartic_myotis.mash_triangle.all.individualChrom.csv") %>% 
  column_to_rownames('...1') %>% 
  as.matrix() %>% 
  as.dist()
df.chr <- dist.chr %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column("genome.hap.scaffold") %>% 
  as_tibble %>% 
  separate("genome.hap.scaffold", c("genome", "hap", "scaffold"), sep="\\.", remove = F)
```

```{r}
Heatmap(
  dist_mat %>% as.matrix,
  name = "mash")
```


```{r}
dist.chr.mat <- dist.chr %>% as.matrix

Heatmap(
  df.chr %>% 
    # select(-starts_with("mMyoAui1"), -starts_with("mMyoYum1", -starts_with)) %>% 
    filter(genome == "mMyoAui1") %>% 
    select(starts_with("mMyoSep"), genome.hap.scaffold) %>% 
    select_if(function(x){any(x!=1, na.rm = T)}) %>% 
    column_to_rownames("genome.hap.scaffold") %>% 
    as.matrix,
  name = "mash", show_row_dend = F, show_column_names = F, show_column_dend = F)

```

```{r}
df.chr %>% 
    # select(-starts_with("mMyoAui1"), -starts_with("mMyoYum1", -starts_with)) %>% 
    filter(genome == "mMyoAui1") %>% 
    select(starts_with("mMyoSep"), genome, hap, scaffold) %>% 
  pivot_longer(-c(genome,hap,scaffold)) %>% 
  group_by(genome, hap, scaffold) %>% 
  filter(value == min(value)) %>% 
  summarize(closest = name, value=value)
```

