---
title: "phylogeny"
author: "Juan Manuel Vazquez"
date: "2023-05-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(tidyverse)
library(magrittr)
library(tidytree)
library(ggtree)
library(ape)
library(naturalsort)
library(taxiz)
```

```{r tree dataframe}
df.chr.tr <- read_tsv('../../analyses/phylo/output/iqtree/20230411_genes_noempty_complete_concat_byChr/alltrees.scaffold.phylo.list', col_names=c("Chr", "phylo"))

tip_order = c(
  "Myotis_lucifugus",
  "Myotis_occultus",
  "Myotis_yumanensis",
  "Myotis_velifer",
  "Myotis_thysanodes",
  "Myotis_evotis",
  "Myotis_auriculus",
  "Myotis_californicus",
  "Myotis_volans",
  "Myotis_myotis"
)


# df.chr.tr.withPhylo<- df.chr.tr %>% mutate(tree = df.chr.tr$phylo %>% {ifelse(is.na(.), NA, read.tree(file=NULL, text=.))})
l.chr.tr <- df.chr.tr %>% select(Chr, phylo) %>% split(.,.$phylo) %>% set_names(., sapply(., . %>% pull(Chr))) %>% lapply(., . %>% pull(phylo) %>% read.tree(file=NULL, text=.) %>% ape::root.phylo(., 'Myotis_myotis', resolve.root=T))

class(l.chr.tr) <- "multiPhylo"

```

```{r species tree }
tr.species <- root.phylo(read.tree(text="(Myotis_auriculus:0.0049530287,(Myotis_californicus:0.0059138183,(((Myotis_lucifugus:0.0030514562,Myotis_occultus:0.0032471934)100/100:0.0020768353,(Myotis_velifer:0.0029764851,Myotis_yumanensis:0.0029904558)100/100:0.0038364895)100/100:0.0009882682,(Myotis_myotis:0.0131977455,Myotis_volans:0.0055379826)100/100:0.0012340035)100/100:0.0023012371)100/100:0.0009098871,(Myotis_evotis:0.0017915030,Myotis_thysanodes:0.0018269795)100/100:0.0020219079);"), outgroup = "Myotis_myotis", resolve.root = T)
```

```{r }
upham.ml <- read.tree("../../data/tree/UphamEtAl2019_Dryad_doi_10.5061/Data_S3_globalRAxML_files/RAxML_bipartitions.result_FIN4_raw_rooted_wBoots_4098mam1out_OK.newick")

upham.ml.ourbats <- upham.ml %>% 
  keep.tip(tip_order[str_detect(tip_order, "occultus", negate = T)] %>% str_c(., "_VESPERTILIONIDAE_CHIROPTERA"))

upham.ml.ourbats$tip.label <- upham.ml.ourbats$tip.label %>% 
  str_remove("_VESPERTILIONIDAE_CHIROPTERA")
```


```{r}
ourtree <- rotate(rotateConstr(master.tree,upham.ml.ourbats$tip.label), 14) %>% 
  drop.tip("Myotis_occultus")

p1 <- rotate(rotateConstr(master.tree,upham.ml.ourbats$tip.label), 14) %>% ggtree(branch.length = F,ladderize = T,) + geom_tiplab() + geom_nodelab(aes(label=node)) # + xlim_tree(c(NA,0.05))

uphamtree <- upham.ml.ourbats

p2 <- uphamtree %>% ggtree(branch.length = F) + geom_tiplab() + geom_nodelab(aes(label=node))# + xlim_tree(c(NA,0.3))


d1 <- p1$data
d2 <- p2$data

d2$x <- max(d2$x) - d2$x + max(d1$x) + 0.01

pp <- p1 + geom_tree(data=d2, branch.length=F)

dd <- bind_rows(d1, d2) %>% 
  filter(!is.na(label))

pp + geom_line(aes(x, y, group=label), data=dd, color='grey') 





```



```{r}
p.chr.trees <- l.chr.tr %>% 
  ggtree() + 
  theme_tree() + 
  geom_tiplab() +
  coord_cartesian(clip = 'off') + 
  facet_wrap(~naturalfactor(.id), scales='free')
```

```{r}
p.chr.trees
```


```{r Data: AnAge}
anage <- read_tsv('../../data/lifehistory/anage_data.txt') %>% 
  mutate(label = str_c(Genus, "_", Species)) %>% 
  rename(size = `Adult weight (g)`,
         lifespan = `Maximum longevity (yrs)`) %>% 
  filter(Class == 'Mammalia')  # I only want mammals
```

```{r Data: panTheria}
panTheria <- read_tsv("../../data/lifehistory/PanTHERIA_1-0_WR05_Aug2008.txt") %>% 
  mutate(label = MSW05_Binomial %>% str_replace_all(" ", "_"),
         lifespan = `17-1_MaxLongevity_m` %>% divide_by(12)) %>% 
  rename(size = `5-1_AdultBodyMass_g`)
```

```{r Data harmonization: AnAge+Pantheria}
anage.taxa <- anage %>% pull(label) %>% str_replace_all('_', " ")
pantheria.taxa <- anage %>% pull(label) %>% str_replace_all('_', " ")
setdiff(panTheria$label, anage$label)
```


```{r Data: DBatVir}
vir <- readxl::read_xls("../../data/DBatVir/DBatVir_From Myotis bats_20230509.xls", skip = 1) %>% 
  mutate(
    label = `From bat` %>% 
      str_replace("^Myotis$", "Myotis_spc.") %>% 
      str_replace_all("Myotis cf. californicus/ciliolabrum BL-2021", "Myotis californicus") %>% 
      str_replace_all("Myotis ciliolabrum", "Myotis californicus") %>% 
      str_replace_all(" ", "_")
  )

vir.summary.familyCount <- vir %>% group_by(label, `Viral family`) %>% dplyr::summarize(n=n())
vir.summary.allCount <- vir %>% group_by(label) %>% dplyr::summarize(n=n())
```

```{r}
p.spc <- tr.species %>% 
  ggtree(branch.length = F) + 
  geom_tiplab() + 
  theme_tree2() + 
  xlim_tree(c(NA, 0.02)) + 
  coord_cartesian(clip='off')

vir.summary.allCount.onlyOurs <- vir.summary.allCount %>% filter(label %in% tr.species$tip.label)
age <- anage %>% 
  filter(label %in% tr.species$tip.label) %>% 
  select(label, lifespan)

dat <- full_join(vir.summary.allCount.onlyOurs, age)

p.spc.data <- p.spc + 
  geom_facet(panel = "N.viruses", data = dat, geom = geom_col, 
               mapping=aes(x = n), orientation = 'y', width = .6) +
  geom_facet(panel = "age", data = dat, geom = geom_col, 
               mapping=aes(x = lifespan), orientation = 'y', width = .6)
p.spc.data
```

```{r}
dat %>% 
  ggplot(
    aes(x=n,
        y=lifespan)
  ) + 
  geom_point() +
  geom_smooth(method = 'lm')
```


