---
title: "Sample Collection Distribution"
author: "Juan Manuel Vazquez"
date: "2022-11-08"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
  
```{r library mapping, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(magick)
library(patchwork)
```

```{r}
our_genomes = c(
  "Myotis_auriculus",
  "Myotis_californicus",
  "Myotis_occultus",
  "Myotis_lucifugus",
  "Myotis_yumanensis",
  "Myotis_volans",
  "Myotis_velifer",
  "Myotis_evotis",
  "Myotis_thysanodes"
)

species_color = ggsci::pal_d3(palette = "category20")(length(our_genomes)+1) %>% 
  set_names(., c(our_genomes, "Other"))
species_color["Myotis_evotis"] = "#17BECFFF"
species_color["Other"] = "#7F7F7FFF"


```


```{r MVZ sample data, include=F, eval=F}
species.dist <- 
  read_csv("../data/Arctos_Myotis_MVZ.csv") %>% 
  rename(latitude= DEC_LAT, longitude = DEC_LONG) #%>% 
filter(!is.na(latitude), !is.na(longitude))

ids_best <- read_lines("../output/sample_goodOrExcellent.txt")
ids_min <- read_lines("../output/sample_all.txt")

species.seq <- species.dist %>% 
  filter(GUID %in% ids_min) %>% 
  mutate(HQ = GUID %in% ids_best)

```

```{r Datasheet, results=F, warning=F}

sheet_cols <- c(
  'CollectionID' = 'c',
  'Source Info & Permit #' = 'c',
  'Date Captured' = 'D',
  'Date Sampled' = 'D',
  'SampleTimeStart' = 't',
  'SampleTimeEnd' = 't',
  'Collector' = 'c',
  'County' = 'c',
  'State' = 'c',
  'LocationShort' = 'c',
  'LocationFull' = 'c',
  'LocationDetails' = 'c',
  'CoordExact' = 'c',
  'What3Words' = 'c',
  'Lattitude' = 'd',
  'Longitude' = 'd',
  'Altitude (ft)' = 'c',
  'Net #' = 'c',
  'FieldSpeciesID' = 'c',
  'FieldSpeciesMethod' = 'c',
  'ConfirmedSpeciesID' = 'c',
  'ConfirmationMethod' = 'c',
  'Sex' = 'c',
  'Age' = 'c',
  'Reproductive Status' = 'c',
  'Weight (g)' = 'd',
  'Forearm (mm)' = 'd',
  'Ear (mm)' = 'd',
  'Tragus (mm)' = 'd',
  'Tail (mm)' = 'd',
  'Thumb (mm)' = 'd',
  'WNS Status' = 'c',
  'HasAccoustic' = 'c',
  'PunchesCollected' = 'c',
  'Preservation' = 'c',
  'OtherSamples' = 'c',
  'OtherMeasurements' = 'c',
  'Comments' = 'c',
  'AltID' = 'c'
)


# datasheet <- read_sheet("https://docs.google.com/spreadsheets/d/1DJctPKAd9TQOLNnmGXP8t0TPAEe4-CICus9QZ7IYsCU/edit#gid=915133740", col_types = sheet_cols %>% paste0(collapse=""))
# datasheet %>% write_tsv("../data/collection_datasheet_2022-11-15.tsv")
datasheet <- read_tsv("../data/collection_datasheet_2022-11-15.tsv", col_types = sheet_cols %>% paste0(collapse=""))
```
```{r Species Shapefiles, results=F, warning=F}
shape.myoAui <- dir(path="../data/USGS_SpeciesRanges/Myotis_auriculus/", pattern = ".shp$", full.names=T) %>% 
  st_read() %>% 
  mutate(species = "Myotis_auriculus") %>% 
  st_make_valid()
shape.myoCai <- dir(path = "../data/USGS_SpeciesRanges/Myotis_californicus/", pattern = ".shp$", full.names=T) %>%
  st_read() %>% 
  mutate(species = "Myotis_californicus") %>% 
  st_make_valid()
shape.myoOcc <- dir(path = "../data/USGS_SpeciesRanges/Myotis_occultus/", pattern = ".shp$", full.names=T) %>%
  st_read() %>% 
  mutate(species = "Myotis_occultus") %>% 
  st_make_valid()
shape.myoLuc <- dir(path = "../data/USGS_SpeciesRanges/Myotis_lucifugus/", pattern = ".shp$", full.names=T) %>%
  st_read() %>% 
  mutate(species = "Myotis_lucifugus") %>% 
  st_make_valid()
shape.myoYum <- dir(path = "../data/USGS_SpeciesRanges/Myotis_yumanensis/", pattern = ".shp$", full.names=T) %>%
  st_read() %>% 
  mutate(species = "Myotis_yumanensis") %>% 
  st_make_valid()
shape.myoVol <- dir(path = "../data/USGS_SpeciesRanges/Myotis_volans/", pattern = ".shp$", full.names=T) %>%
  st_read() %>% 
  mutate(species = "Myotis_volans") %>% 
  st_make_valid()
shape.myoVel <- dir(path = "../data/USGS_SpeciesRanges/Myotis_velifer/", pattern = ".shp$", full.names=T) %>%
  st_read() %>% 
  mutate(species = "Myotis_velifer") %>% 
  st_make_valid()
shape.myoEvo <- dir(path = "../data/USGS_SpeciesRanges/Myotis_evotis/", pattern = ".shp$", full.names=T) %>%
  st_read() %>% 
  mutate(species = "Myotis_evotis") %>% 
  st_make_valid()
shape.myoThy <- dir(path = "../data/USGS_SpeciesRanges/Myotis_thysanodes/", pattern = ".shp$", full.names=T) %>%
  st_read() %>% 
  mutate(species = "Myotis_thysanodes") %>% 
  st_make_valid()
```


```{r base maps}
world <- ne_countries(scale = "medium", returnclass = "sf") %>% 
  st_make_valid()
northAmerica <- ne_countries(scale = "medium", returnclass = "sf", country = c("United States of America", "Mexico", "Canada")) %>% st_make_valid
# class(world)
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
west <- subset(states, ID %in% c("california", "arizona", "nevada", "new mexico", "idaho", "oregon", "washington", "montana", "nebraska", "colorado", "utah", "wyoming"))
notwest <- subset(states, !(ID %in% c("california", "arizona", "nevada", "new mexico", "idaho", "oregon", "washington", "montana", "nebraska", "colorado", "utah", "wyoming")))
cal <- subset(states, ID == "california")
calaz <- subset(states, ID %in% c("california", "arizona"))
caaznv <- subset(states, ID %in% c("california", "arizona", "nevada"))
notcalaz <- subset(states, !(ID %in% c("california", "arizona")))
```

```{r only collection points}
datasheet.known <- datasheet %>% 
  filter(!is.na(Lattitude)) %>% 
  select(species=FieldSpeciesID, Lattitude, Longitude) #%>% 
  # mutate(species = species %>% str_replace_all(" ", "_"))
p.map.collections <- ggplot() + 
  geom_sf(data= west, color = "#ABB0B8", fill = "#6F7378", size = 0.1) +
  geom_spatial_point(data= datasheet.known, aes(group=species, y=Lattitude, x=Longitude, color=species), size=4, position="jitter") + 
  geom_spatial_label_repel(data= datasheet.known, aes(label=species,group=species, y=Lattitude, x=Longitude, color=species), show.legend=F) + 
  scale_color_manual(values = species_color %>% set_names(., names(.) %>% str_replace_all("_", " "))) +
  ggpubr::theme_pubclean() + 
  theme(legend.position = "none")

p.map.collections
```

```{r Minimal collections map}
p.map.collections.caaznv <- ggplot() + 
  geom_sf(data= caaznv, color = "#ABB0B8", fill = "#6F7378", size = 0.1) +
  geom_spatial_point(data= datasheet.known, aes(group=species, y=Lattitude, x=Longitude, fill=species), size=4, pch=21, position="jitter") + 
  geom_spatial_label_repel(data= datasheet.known, aes(label=species,group=species, y=Lattitude, x=Longitude, fill=species), show.legend=F, color='black', nudge_x=-0.5) + 
  scale_color_manual(values = species_color %>% set_names(., names(.) %>% str_replace_all("_", " "))) +
  scale_fill_manual(values = species_color %>% set_names(., names(.) %>% str_replace_all("_", " "))) +
  ggpubr::theme_pubclean() + 
  theme(legend.position = "none")

p.map.collections.caaznv
```


```{r [FAILING] intersections to improve looks, eval=F}
shape.myoLuc$geometry <- shape.myoLuc$geometry %>%
  s2::s2_rebuild() %>%
  sf::st_as_sfc()
sf::sf_use_s2(TRUE)
st_intersection(west, shape.myoLuc)
shape.myoLuc2 <- st_transform(shape.myoLuc, "NAD83")
st_crs(shape.myoLuc)
st_crs(shape.myoLuc2)
st_crs(west)
west2 <- st_transform(west, crs="NAD83")
st_crs(west2)
shape.myoLuc3 <- shape.myoLuc
st_crs(shape.myoLuc3) <- "NAD83"
st_intersection(shape.myoLuc3, west2)
```


```{r myotis ranges split}
p.mapMyo.split <- ggplot() + 
  geom_sf(data= west, color = "#ABB0B8", fill = "#6F7378", size = 0.1) + 
  annotation_spatial(data = shape.myoLuc, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data = shape.myoYum, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data = shape.myoCai, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data = shape.myoVol, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data = shape.myoEvo, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data = shape.myoThy, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data = shape.myoOcc, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data = shape.myoVel, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data = shape.myoAui, aes(group = species, fill=species), alpha = 0.8, color="black") +
  annotation_spatial(data=notwest, fill="white", color="white") +
  geom_spatial_point(data= datasheet.known, aes(group=species, y=Lattitude, x=Longitude), size=2) + 
  scale_fill_manual("Species", values = species_color) +
  scale_color_manual("Species", values = species_color) +
  guides(fill=guide_none()) + 
  theme_void() +
  facet_wrap(~species) + 
  theme(
    strip.text = element_text(face="bold", size=12, hjust = 0.5)
  )
p.mapMyo.split
#%>% plotly::ggplotly()
```

```{r myotis pictures}
pic.myoLuc <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/108746-19-e1593640880404.jpg") %>% image_ggplot()
pic.myoYum <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/106605-56-812x600.jpg") %>% image_ggplot()
pic.myoCai <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/106608-56-812x600.jpg") %>% image_ggplot()
pic.myoVol <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/106442-19-812x600.jpg") %>% image_ggplot()
pic.myoEvo <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/Long-eared-Myotis-MYOTIS-EVOTIS-Michael-DurhamMinden-PIctures-e1642201106124-812x600.jpeg") %>% image_ggplot()
pic.myoThy <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/106472-19.jpg") %>% image_ggplot()
pic.myoOcc <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/Arizona-myotis-Rick-and-Nora-Bowers-Alamy-Stock-Photo--812x600.jpeg") %>% image_ggplot()
pic.myoVel <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/106463-19-e1642201625671-812x600.jpg") %>% image_ggplot()
pic.myoAui <- image_read("https://www.batcon.org/wp-content/uploads/2020/02/106475-19-e1593638188243-812x600.jpg") %>% image_ggplot()
```

```{r myotis ranges split with photo}
p.map.base <- ggplot() + 
  geom_sf(data= west, color = "#ABB0B8", fill = "#6F7378", size = 0.1)

p.map.myoLuc <- p.map.base + 
  annotation_spatial(data = shape.myoLuc, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis lucifugus") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_lucifugus"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoYum <- p.map.base + 
  annotation_spatial(data = shape.myoYum, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis yumanensis") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_yumanensis"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoCai <- p.map.base + 
  annotation_spatial(data = shape.myoCai, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis californicus") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_californicus"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoVol <- p.map.base + 
  annotation_spatial(data = shape.myoVol, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis volans") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_volans"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoEvo <- p.map.base + 
  annotation_spatial(data = shape.myoEvo, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis evotis") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_evotis"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoThy <- p.map.base + 
  annotation_spatial(data = shape.myoThy, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis thysanodes") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_thysanodes"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoOcc <- p.map.base + 
  annotation_spatial(data = shape.myoOcc, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis occultus") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_occultus"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoVel <- p.map.base + 
  annotation_spatial(data = shape.myoVel, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis velifer") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_velifer"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoAui <- p.map.base + 
  annotation_spatial(data = shape.myoAui, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notwest, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=12, hjust = 0.5), 
        plot.background = element_rect(color="black"), 
        plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis auriculus") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_auriculus"), aes(group=species, y=Lattitude, x=Longitude), size=2)


p.map.pic.myoLuc <- p.map.myoLuc + inset_element(pic.myoLuc, left = 0.69, bottom = 0.6, right = 1, top = 1)
p.map.pic.myoYum <- p.map.myoYum + inset_element(pic.myoYum, left = 0.69, bottom = 0.6, right = 1, top = 1)
p.map.pic.myoCai <- p.map.myoCai + inset_element(pic.myoCai, left = 0.69, bottom = 0.6, right = 1, top = 1)
p.map.pic.myoVol <- p.map.myoVol + inset_element(pic.myoVol, left = 0.69, bottom = 0.6, right = 1, top = 1)
p.map.pic.myoEvo <- p.map.myoEvo + inset_element(pic.myoEvo, left = 0.69, bottom = 0.6, right = 1, top = 1)
p.map.pic.myoThy <- p.map.myoThy + inset_element(pic.myoThy, left = 0.69, bottom = 0.6, right = 1, top = 1)
p.map.pic.myoOcc <- p.map.myoOcc + inset_element(pic.myoOcc, left = 0.69, bottom = 0.6, right = 1, top = 1)
p.map.pic.myoVel <- p.map.myoVel + inset_element(pic.myoVel, left = 0.69, bottom = 0.6, right = 1, top = 1)
p.map.pic.myoAui <- p.map.myoAui + inset_element(pic.myoAui, left = 0.69, bottom = 0.6, right = 1, top = 1)

p.mapPic <- (p.map.pic.myoLuc | p.map.pic.myoYum | p.map.pic.myoCai)/
  (p.map.pic.myoVol | p.map.pic.myoEvo | p.map.pic.myoThy)/
  (p.map.pic.myoOcc | p.map.pic.myoVel | p.map.pic.myoAui)

p.mapPic
```

```{r only CA AZ}
p.map.base.calaz <- ggplot() + 
  geom_sf(data= calaz, color = "#ABB0B8", fill = "#6F7378", size = 0.1)

p.map.myoLuc.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoLuc, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis lucifugus") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_lucifugus"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoYum.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoYum, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis yumanensis") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_yumanensis"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoCai.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoCai, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis californicus") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_californicus"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoVol.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoVol, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis volans") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_volans"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoEvo.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoEvo, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis evotis") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_evotis"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoThy.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoThy, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis thysanodes") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_thysanodes"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoOcc.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoOcc, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis occultus") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_occultus"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoVel.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoVel, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis velifer") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_velifer"), aes(group=species, y=Lattitude, x=Longitude), size=2)
p.map.myoAui.calaz <- p.map.base.calaz + 
  annotation_spatial(data = shape.myoAui, aes(group = species, fill=species), alpha = 0.8, color="black") + 
  annotation_spatial(data=notcalaz, fill="white", color="white") + 
  scale_fill_manual(values = species_color) + 
  guides(fill=guide_none()) + 
  theme_void() + 
  theme(title = element_text(face="bold", size=10, hjust = 0.5), plot.margin = margin(0,0,0,0, "cm")) + 
  ggtitle("Myotis auriculus") +
  geom_spatial_point(data= datasheet.known %>% filter(species == "Myotis_auriculus"), aes(group=species, y=Lattitude, x=Longitude), size=2)


p.map.pic.myoLuc.calaz <- p.map.myoLuc.calaz + inset_element(pic.myoLuc, left = 0.4, bottom = 0.55, right = 1, top = 0.95)
p.map.pic.myoYum.calaz <- p.map.myoYum.calaz + inset_element(pic.myoYum, left = 0.4, bottom = 0.55, right = 1, top = 0.95)
p.map.pic.myoCai.calaz <- p.map.myoCai.calaz + inset_element(pic.myoCai, left = 0.4, bottom = 0.55, right = 1, top = 0.95)
p.map.pic.myoVol.calaz <- p.map.myoVol.calaz + inset_element(pic.myoVol, left = 0.4, bottom = 0.55, right = 1, top = 0.95)
p.map.pic.myoEvo.calaz <- p.map.myoEvo.calaz + inset_element(pic.myoEvo, left = 0.4, bottom = 0.55, right = 1, top = 0.95)
p.map.pic.myoThy.calaz <- p.map.myoThy.calaz + inset_element(pic.myoThy, left = 0.4, bottom = 0.55, right = 1, top = 0.95)
p.map.pic.myoOcc.calaz <- p.map.myoOcc.calaz + inset_element(pic.myoOcc, left = 0.4, bottom = 0.55, right = 1, top = 0.95)
p.map.pic.myoVel.calaz <- p.map.myoVel.calaz + inset_element(pic.myoVel, left = 0.4, bottom = 0.55, right = 1, top = 0.95)
p.map.pic.myoAui.calaz <- p.map.myoAui.calaz + inset_element(pic.myoAui, left = 0.4, bottom = 0.55, right = 1, top = 0.95)

p.mapPic.calaz <- 
  (p.map.pic.myoLuc.calaz | p.map.pic.myoYum.calaz | p.map.pic.myoCai.calaz)/
  (p.map.pic.myoVol.calaz | p.map.pic.myoEvo.calaz | p.map.pic.myoThy.calaz)/
  (p.map.pic.myoOcc.calaz | p.map.pic.myoVel.calaz | p.map.pic.myoAui.calaz)

p.mapPic.calaz
```




