---
title: "StableTraits"
author: "docmanny"
date: "2023-10-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r Libraries and functions, include = F}
knitr::opts_chunk$set(eval=T, 
                      #echo=F, message = F, warning = F, 
                      out.width="6in", fig.pos = "H", out.extra = "",
                      fig.retina = 2, dpi = 300, dev=c('cairo_pdf', 'svg', 'png','cairo_ps'))

# if(basename(getwd()) != "paper_PLOS") setwd("paper_PLOS")

set.seed(1234)
library(data.table)
library(tidyverse)
library(magrittr)
library(viridis)
options(readr.num_columns = 0)
library(ape)
library(geiger)
library(nlme)
library(treeio)
library(tidytree)
library(ggtree)
library(ggimage)
library(ggpubr)
library(ggsci)
library(ggstance)
library(plotly)
library(ggplotify)
library(UpSetR)
library(ggrepel)
library(magick)
library(gghighlight)
library(broom.mixed)
library(purrr)
library(kableExtra)
library(stargazer)
library(ggnewscale)
library(ComplexHeatmap)
library(rms)
library(patchwork)
```

```{r}
rates_tree <- read.tree('../data/stableTraits/UphamEtAl2019WithBS_Run1_2.rates_tree')
sq_tree <- read.tree('../data/stableTraits/UphamEtAl2019WithBS_Run1_2.sqchange_tree')
brlens <- read_tsv('../data/stableTraits/UphamEtAl2019WithBS_Run1_2.brlens')
ancstates <- read_tsv('../data/stableTraits/UphamEtAl2019WithBS_Run1_2.ancstates')
```

