---
title: "TOGA_genes_per_scaffold"
author: "Juan M Vazquez (docmanny)"
date: "2022-12-05"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(tidyverse)
library(naturalsort)
library(ggpubr)
```

```{r}
toga.vel <- read_tsv("/mnt/c/users/manue/OneDrive/Desktop/query_annotation.bed", col_types = "cddcdcddcdcc",
              col_names=c("chr", "s", "e", "name", "score", "strand", "thickStart", "thickEnd", "RBG", "nBlock", "blockStart", "blockLength" ))

toga.vel 
```

```{r}
genome.vel <- read_tsv("../../analyses/makeHub/data/genomes/mMyoVel1.genome", col_names = c("chr", "length"))

genome.vel
```


```{r}
toga.vel.summary <- toga.vel %>% 
  group_by(chr) %>% 
  summarize(n_genes = n_distinct(name)) %>% 
  left_join(genome.vel, by="chr") %>% 
  mutate(chr = factor(chr, levels=str_sort(chr, numeric = T) %>% unique))
```

```{r}
toga.vel.summary %>% 
  ggplot(
    aes(x=length, y=n_genes, label=chr)
  ) + 
  geom_text(aes(color=(as.numeric(chr)<=23))) + 
  theme_pubclean() + 
  scale_x_log10() + 
  scale_y_log10() + 
  ggtitle("TOGA: mMyoVel1 (hg38)")
```

```{r}
toga.luc <- read_tsv("/mnt/c/users/manue/OneDrive/Desktop/TOGA_mMyoLuc1_hg38.bed", col_types = "cddcdcddcdcc",
              col_names=c("chr", "s", "e", "name", "score", "strand", "thickStart", "thickEnd", "RBG", "nBlock", "blockStart", "blockLength" ))

toga.luc 
```

```{r}
genome.luc <- read_tsv("../../analyses/makeHub/data/genomes/mMyoLuc1.genome", col_names = c("chr", "length"))

genome.luc
```


```{r}
toga.luc.summary <- toga.luc %>% 
  group_by(chr) %>% 
  summarize(n_genes = n_distinct(name)) %>% 
  left_join(genome.luc, by="chr") %>% 
  mutate(chr = factor(chr, levels=str_sort(chr, numeric = T) %>% unique))
```

```{r}
toga.luc.summary %>% 
  ggplot(
    aes(x=length, y=n_genes, label=chr)
  ) + 
  geom_text(aes(color=(as.numeric(chr)<=23))) + 
  theme_pubclean() + 
  scale_x_log10() + 
  scale_y_log10() + 
  ggtitle("TOGA: mMyoLuc1 (hg38)")
```

