---
title: "RICR Doubletree Figs"
author:
    - "Juan M Vazquez"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 3
  toc_float:
    collapsed: no
    smooth_scroll: yes
---

```{r Libraries and functions, include = F}
knitr::opts_chunk$set(eval=T, 
                      #echo=F, message = F, warning = F, 
                      out.width="6in", fig.pos = "H", out.extra = "",
                      fig.retina = 2, dpi = 300, dev=c('cairo_pdf', 'svg', 'png','cairo_ps'))

# if(basename(getwd()) != "paper_PLOS") setwd("paper_PLOS")

set.seed(1234)
library(data.table)
library(tidyverse)
library(magrittr)
library(viridis)
options(readr.num_columns = 0)
library(ape)
library(geiger)
library(nlme)
library(treeio)
library(tidytree)
library(ggtree)
library(ggimage)
library(ggpubr)
library(ggsci)
library(ggstance)
library(plotly)
library(ggplotify)
library(UpSetR)
library(ggrepel)
library(magick)
library(gghighlight)
library(broom.mixed)
library(purrr)
library(kableExtra)
library(stargazer)
library(ggnewscale)
library(ComplexHeatmap)
library(rms)
library(patchwork)
library(ggwordcloud)
# source("../code/generalFunctions.R")
```

```{r}
# print("start")
# warning("start")
input.tree.csv <- snakemake@input[[1]]
html.f = snakemake@output[["html"]]
bodysize.f = sprintf("figures/RICR/%s-bodySize.pdf",snakemake@wildcards[["clade"]])
lifespan.f = sprintf("figures/RICR/%s-lifespan.pdf",snakemake@wildcards[["clade"]])
RICR.f = sprintf("figures/RICR/%s-RICR.pdf",snakemake@wildcards[["clade"]])
doubletree.f = sprintf("figures/RICR/%s-DoubleTree.pdf",snakemake@wildcards[["clade"]])

```


```{r}
# print(input.tree.csv)
# tree.clade.table <- read_csv("../output/pubFiles/bodysize-Eutheria.csv") %>%
tree.clade.table <- read_csv("../../xenarthraRICR/output/pubFiles/cancerRisk-Eutheria.csv") %>%
# tree.clade.table <- read_csv(input.tree.csv) %>% 
  mutate(label=str_replace_all(label, " ", "."))

class(tree.clade.table) %<>% str_replace("tbl_df", "tbl_tree")

#tree.clade.table[tree.clade.table$lnSize==999,c("lnSize", "lnSize.low", "lnSize.high")] <- NA

tree.clade <- tree.clade.table %>% as.treedata()


dat.clade <- tree.clade.table %>% 
  dplyr::select(-parent, -node, -branch.length)

size.scale <- tree.clade.table %>% pull(lnSize) %>% unique %>% as.numeric() %>% sort
size.scale.min <- size.scale[1]
size.scale.max <- size.scale[length(size.scale)]
get.size.color <- function(n, scale = size.scale){
  scale.colors = viridis::viridis(n=length(scale)) %>% 
    set_names(., as.character(scale))
  scale.colors[as.character(n)]
}

lifespan.scale <- tree.clade.table %>% pull(Lifespan) %>% unique %>% as.numeric() %>% sort
lifespan.scale.min <- lifespan.scale[1]
lifespan.scale.max <- lifespan.scale[length(lifespan.scale)]
get.lifespan.color <- function(n, scale = lifespan.scale){
  scale.colors = viridis::viridis(n=length(scale), option = "C") %>% 
    set_names(., as.character(scale))
  scale.colors[as.character(n)]
}

scale.log2CancerSucceptabilityChange <- tree.clade.table %>% 
  pull(log2CancerSucceptabilityChange) %>% 
  unique %>% 
  as.numeric() %>% 
  sort %>% 
  set_names(.,.)
scale.log2CancerSucceptabilityChange.min <- min(scale.log2CancerSucceptabilityChange)
scale.log2CancerSucceptabilityChange.max <- scale.log2CancerSucceptabilityChange[length(scale.log2CancerSucceptabilityChange)]

get.log2CancerSucceptabilityChange.color <- function(n, scale = scale.log2CancerSucceptabilityChange){
  scale.colors = viridis::viridis(n=length(scale)) %>% 
    set_names(., as.character(scale))
  scale.colors[as.character(n)]
}


size.scale.expanded <- c(size.scale, dat.clade$lnSize.low, dat.clade$lnSize.high) %>% unique %>% as.numeric() %>% sort
size.scale.expanded.min <- size.scale.expanded[1]
size.scale.expanded.max <- size.scale.expanded[length(size.scale.expanded)]

lifespan.scale.expanded <- c(lifespan.scale, tree.clade.table$Lifespan.low, tree.clade.table$Lifespan.high) %>% unique %>% as.numeric() %>% sort
lifespan.scale.expanded.min <- lifespan.scale.expanded[1]
lifespan.scale.expanded.max <- lifespan.scale.expanded[length(lifespan.scale.expanded)]



```

```{r}
nodes.highlight <- list( 
  # Chelonoidis = tree.clade.table %>% filter(str_detect(label, "^Chelonoidis")) %>% pull(node),
  # Chiroptera = MRCA(tree.clade, 'Myotis.lucifugus', 'Pteropus.vampyrus'),
  Myotis = tree.clade.table %>% filter(str_detect(label, "^Myotis")) %>% pull(node)
  # Vespertilliodinae = MRCA(tree.clade, "Myotis.lucifugus", "Miniopterus.schreibersi")
) %>% 
  lapply(., 
         function(x, t=tree.clade){
           a = expand.grid(x,x) %T>%
             print %>% 
             filter(Var1!=Var2) %>% 
             rowwise() %T>%
             print %>% 
             mutate(mrca=MRCA(t, Var1, Var2)) %>% 
             unlist %>% 
             unique
         })
nodes.label.highlight <- tree.clade.table %>% 
  filter(node %in% (nodes.highlight %>% unlist %>% unname)) %>% 
  pull(label)
```


```{r Plot-Bodysize, include=F}
# print(bodysize.f)
p.bodysize.clade <- dat.clade %>%
  filter(label %in% nodes.label.highlight) %>% 
  ggplot(
    aes(
      y=as.factor(label),
      x=lnSize, 
      xmin=lnSize.low,
      xmax=lnSize.high
      )
  ) +
  geom_pointrange(size=0.5) +
  geom_point(aes(color=lnSize), size=1) +
  geom_point(aes(x=lnSize.low, color=lnSize.low), size=1.5, stroke=2, pch="[") +
  geom_point(aes(x=lnSize.high, color=lnSize.high), size=1.5, stroke=2, pch="]") +
  scale_color_distiller(limits=c(size.scale.expanded.min, size.scale.expanded.max), 
                        palette = "Blues", 
                        direction = 1,
                        guide = guide_colorbar(
                          title="Body size (log)",
                          title.theme =  element_text(size = 6, face = "bold", colour = "black"),
                          title.position = "top",
                          title.hjust = 0.5
                          )
                        ) +
  labs(
    x="Body size (95%CI)",
    y="Node"
  ) + 
  theme_pubclean()+
  labs_pubr() + 
  theme(
    text = element_text(face = "plain", 
                        colour = "black", lineheight = 0.9, 
                        hjust = 0.5, vjust = 0.5, angle = 0, margin = margin(), 
                        debug = FALSE), 
    axis.text = element_text(size = 6, 
                               colour = "black", face = "bold"),
    axis.title = element_text(size = 8, 
                              colour = "black", face = "bold"),
    plot.title = element_text(size = 8, 
                              colour = "black", lineheight = 1, face = "bold"), 
    legend.text = element_text(size = 6, 
                               face = "plain", colour = "black"),
    legend.position = "bottom"
  )
ggsave(bodysize.f, plot=p.bodysize.clade, width=12, height = 9, units="in", dpi=1200, device = cairo_pdf)
p.bodysize.clade
```

```{r Plot-Lifespan-clade}
# print(lifespan.f)
p.lifespan.clade <- dat.clade %>%
  filter(label %in% nodes.label.highlight) %>% 
  ggplot(
    aes(
      y=as.factor(label),
      x=Lifespan, 
      xmin=Lifespan.low,
      xmax=Lifespan.high
      )
  ) +
  geom_pointrange(size=0.5) +
  geom_point(aes(color=Lifespan), size=1) +
  geom_point(aes(x=Lifespan.low, color=Lifespan.low), size=1.5, stroke=2, pch="[") +
  geom_point(aes(x=Lifespan.high, color=Lifespan.high), size=1.5, stroke=2, pch="]") +
  # scale_color_viridis_c(
  #   limits=c(lifespan.scale.expanded.min, lifespan.scale.expanded.max), 
  #   option = "C", 
  #   guide = guide_colorbar(
  #     title="Lifespan (yrs)",
  #     title.theme =  element_text(size = 6, face = "bold", colour = "black"),
  #     title.position = "top",
  #     title.hjust = 0.5
  #   )
  # ) +
  scale_color_distiller(
    palette = "Reds", direction = 1,
    guide = guide_colorbar(
      title="Lifespan (yrs)",
      title.theme =  element_text(size = 6, face = "bold", colour = "black"),
      title.position = "top",
      title.hjust = 0.5
    )
  ) + 
  labs(
    x="Estimated Lifespan from Body Sizes and Body Size 95% CI",
    y="Node"
  ) + 
  theme_pubclean()+
  labs_pubr() + 
  theme(
    text = element_text(face = "plain", 
                        colour = "black", lineheight = 0.9, 
                        hjust = 0.5, vjust = 0.5, angle = 0, margin = margin(), 
                        debug = FALSE), 
    axis.text = element_text(size = 6, 
                               colour = "black", face = "bold"),
    axis.title = element_text(size = 8, 
                              colour = "black", face = "bold"),
    plot.title = element_text(size = 8, 
                              colour = "black", lineheight = 1, face = "bold"), 
    legend.text = element_text(size = 6, 
                               face = "plain", colour = "black"),
    legend.position = "bottom"
  )
ggsave(lifespan.f, plot=p.lifespan.clade, width=12, height = 9, units="in", dpi=1200, device = cairo_pdf)
p.lifespan.clade
```

```{r Plot-RICR-clade}
# print(RICR.f)

dat.clade.sortRICR <- dat.clade %>% 
  mutate(
    label = factor(
      label, 
      levels = dat.clade %>% select(label, log2CancerSucceptabilityChange) %>% arrange(log2CancerSucceptabilityChange) %>% pull(label)
    )
  )

p.RICR.clade <- dat.clade.sortRICR %>%
  filter(label %in% nodes.label.highlight) %>% 
  ggplot(
    aes(
      y=as.factor(label),
      x=log2CancerSucceptabilityChange, 
      # xmin=log2CancerSucceptabilityChange.low,
      # xmax=log2CancerSucceptabilityChange.high
      )
  ) +
  scale_color_viridis_c(
    option = "C",
    guide = guide_colorbar(
      title="Cancer Risk (log2)",
      title.theme =  element_text(size = 6, face = "bold", colour = "black"),
      title.position = "left",
      title.hjust = 0.5, 
      title.vjust = 0.75,
      reverse = T,
      order = 2
    )
  ) +
  # geom_pointrange(size=0.5) +
  geom_point(aes(color=Lifespan), size=1) +
  # geom_point(aes(x=Lifespan.low, color=log2CancerSucceptabilityChange.low), size=1.5, stroke=2, pch="[") +
  # geom_point(aes(x=Lifespan.high, color=log2CancerSucceptabilityChange.high), size=1.5, stroke=2, pch="]") +
  labs(
    x="Estimated RICR from Estimated Body Sizes and Lifespans",
    y="Node"
  ) + 
  theme_pubclean()+
  labs_pubr() + 
  theme(
    text = element_text(face = "plain", 
                        colour = "black", lineheight = 0.9, 
                        hjust = 0.5, vjust = 0.5, angle = 0, margin = margin(), 
                        debug = FALSE), 
    axis.text = element_text(size = 6, 
                               colour = "black", face = "bold"),
    axis.title = element_text(size = 8, 
                              colour = "black", face = "bold"),
    plot.title = element_text(size = 8, 
                              colour = "black", lineheight = 1, face = "bold"), 
    legend.text = element_text(size = 6, 
                               face = "plain", colour = "black"),
    legend.position = "bottom"
  )
ggsave(RICR.f, plot=p.RICR.clade, width=12, height = 9, units="in", dpi=1200, device = cairo_pdf)
p.RICR.clade
```

```{r Plot-DoubleTree-Bodysize-CancerSuscept, include=F}
# print(doubletree.f)
### Body Size ###

p.tree.clade.genomes <- tree.clade %>% 
  ggtree(
    aes(color=as.numeric(lnSize)),
    branch.length = "sqrt.rate"
  )


### Cancer Suscept ###
tree.clade.table <-  tree.clade.table %>%  
  mutate(branch.length = log2CancerSucceptabilityChange %>% abs()) %>% 
  as.treedata

p.tree.clade.table <- tree.clade.table %>% 
  ggtree(
    aes(color=as.numeric(log2CancerSucceptabilityChange))
  )

### Double Tree ###

d.dbltree.3 <- p.tree.clade.genomes$data
d.dbltree.4 <- p.tree.clade.table$data

d.dbltree.4$x <- max(d.dbltree.4$x) - d.dbltree.4$x + max(d.dbltree.3$x) + 500

p.dbltree.all <-
  tree.clade %>% 
  ggtree(., branch.length = "sqrt.rate", aes(color=lnSize, fill=lnSize), size=1) +
  # scale_color_distiller("Body size (log)", palette = "Blues", direction = 1) + 
  scale_color_distiller(
    limits=c(size.scale.expanded.min, size.scale.expanded.max), 
    palette = "Blues", 
    direction = 1,
    guide = guide_colorbar(
      title="Body size (log)",
      title.theme =  element_text(size = 6, face = "bold", colour = "black"),
      title.position = "left",
      title.hjust = 0.5, 
      title.vjust = 0.75,
      order = 1
    )
    # guide=guide_none()
  ) +
  scale_fill_distiller(
    limits=c(lifespan.scale.expanded.min, lifespan.scale.expanded.max), 
    palette = "Reds", 
    direction = 1,
    guide = guide_colorbar(
      title="Lifespan",
      title.theme =  element_text(size = 6, face = "bold", colour = "black"),
      title.position = "left",
      title.hjust = 0.5, 
      title.vjust = 0.75,
      order = 3
    )
    # guide=guide_none()
  ) +
  geom_nodepoint(size=2) + 
  geom_tippoint(size=2) +
  # geom_tiplab(aes(label = if_else(is.na(Genome), "", label)), 
  #             x=(min(d.dbltree.4$x)+max(d.dbltree.3$x))/2, color="black", hjust = 0.5) +
  geom_text_repel(aes(label = if_else(is.na(label), "", label %>% str_replace_all("\\.", " "))), direction = "y", force = 0.5, segment.size = NA, size=2.5,
                  x=(min(d.dbltree.4$x)+max(d.dbltree.3$x))/2, color="black", hjust = 0.5) +
  new_scale_color() + 
  geom_tree(data=d.dbltree.4, aes(color=log2CancerSucceptabilityChange), inherit.aes = F, size=1) + 
  geom_nodepoint(data=d.dbltree.4, aes(color=log2CancerSucceptabilityChange, x=x, y=y), inherit.aes = F, size=2) + 
  geom_tippoint(data=d.dbltree.4, aes(color=log2CancerSucceptabilityChange, x=x, y=y), inherit.aes = F, size=2) +
  # scale_color_viridis_c(option = "D") + 
  # scale_color_distiller(
  #   palette = "Reds", direction = 1,
  #   guide = guide_colorbar(
  #     title="Cancer Risk (log2)",
  #     title.theme =  element_text(size = 6, face = "bold", colour = "black"),
  #     title.position = "top",
  #     title.hjust = 0.5
  #   )
  # ) + 
  scale_color_viridis_c(
    option = "C",
    guide = guide_colorbar(
      title="Cancer Risk (log2)",
      title.theme =  element_text(size = 6, face = "bold", colour = "black"),
      title.position = "left",
      title.hjust = 0.5, 
      title.vjust = 0.75,
      reverse = T,
      order = 2
    )
  ) +
  theme(
    plot.background = element_rect(fill="grey", color="grey"),
    panel.background = element_rect(fill="grey", color="grey"),
  legend.text = element_text(
    size = 6, 
    face = "plain", colour = "black"
  ),
    legend.background = element_blank(),
  legend.position = c(0.5, 0.15),#"bottom",
  legend.box = "vertical",
  legend.direction = "horizontal",
  legend.box.just = "right",
  legend.spacing.y = unit(0.5,"mm")
  # legend.direction = "vertical"
  )

ggsave(doubletree.f, plot=p.dbltree.all, width=12, height = 9, units="in", dpi=1200, device = cairo_pdf)
p.dbltree.all
```

```{r}
save.image(file = sprintf("%s-RICR.Rdata",snakemake@wildcards[["clade"]]),
           compress=T)
```

